spring:
  application:
    name: dto-service
#  datasource:
#    url: jdbc:postgresql://localhost:5433/postgres
#    username: postgres
#    password: postgres
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#    show_sql: true
#  main:
#    web-application-type: servlet
#
server:
  port: 8081